Part 1：Dataset Understanding

In [7]:
#1. Load datasets

import pandas as pd
sold = pd.read_csv("combined_sold_202401_202604_residential.csv")
listing = pd.read_csv("combined_listing_202401_202604_residential.csv")

#2. Dataset dimensions
print("=== SOLD ===")
print(f"Rows: {sold.shape[0]:,}")
print(f"Columns: {sold.shape[1]}")

print("\n=== LISTING ===")
print(f"Rows: {listing.shape[0]:,}")
print(f"Columns: {listing.shape[1]}")

#3. Preview the datasets
sold.head()
listing.head()

#4. Review column names
sold.columns
listing.columns

#5. Review data types
sold.info()
listing.info()

/var/folders/j5/58l4k_310d7g3m6jv7qw33z80000gn/T/ipykernel_98495/936596814.py:4: DtypeWarning: Columns (0,1,4,78,79,80) have mixed types. Specify dtype option on import or set low_memory=False.
  sold = pd.read_csv("combined_sold_202401_202604_residential.csv")
/var/folders/j5/58l4k_310d7g3m6jv7qw33z80000gn/T/ipykernel_98495/936596814.py:5: DtypeWarning: Columns (43) have mixed types. Specify dtype option on import or set low_memory=False.
  listing = pd.read_csv("combined_listing_202401_202604_residential.csv")

=== SOLD ===
Rows: 350,179
Columns: 82

=== LISTING ===
Rows: 547,162
Columns: 84
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350179 entries, 0 to 350178
Data columns (total 82 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   BuyerAgentAOR                 299303 non-null  object
 1   ListAgentAOR                  303996 non-null  object
 2   Flooring                      224124 non-null  object
 3   ViewYN                        320263 non-null  object
 4   WaterfrontYN                  219 non-null     object
 5   BasementYN                    6866 non-null    object
 6   PoolPrivateYN                 321447 non-null  object
 7   OriginalListPrice             349518 non-null  float64
 8   ListingKey                    350179 non-null  int64
 9   ListAgentEmail                349228 non-null  object
 10  CloseDate                     350179 non-null  object
 11  ClosePrice                    350178 non-null  float64
 12  ListAgentFirstName            347640 non-null  object
 13  ListAgentLastName             350140 non-null  object
 14  Latitude                      334346 non-null  float64
 15  Longitude                     334346 non-null  float64
 16  UnparsedAddress               349836 non-null  object
 17  PropertyType                  350179 non-null  object
 18  LivingArea                    349984 non-null  float64
 19  ListPrice                     350179 non-null  float64
 20  DaysOnMarket                  350179 non-null  int64
 21  ListOfficeName                350179 non-null  object
 22  BuyerOfficeName               344830 non-null  object
 23  CoListOfficeName              83721 non-null   object
 24  ListAgentFullName             350088 non-null  object
 25  CoListAgentFirstName          80702 non-null   object
 26  CoListAgentLastName           80912 non-null   object
 27  BuyerAgentMlsId               349721 non-null  object
 28  BuyerAgentFirstName           348505 non-null  object
 29  BuyerAgentLastName            350031 non-null  object
 30  FireplacesTotal               0 non-null       float64
 31  AssociationFeeFrequency       146005 non-null  object
 32  AboveGradeFinishedArea        0 non-null       float64
 33  ListingKeyNumeric             350179 non-null  int64
 34  MLSAreaMajor                  303277 non-null  object
 35  TaxAnnualAmount               0 non-null       float64
 36  CountyOrParish                350179 non-null  object
 37  MlsStatus                     350179 non-null  object
 38  ElementarySchool              46012 non-null   object
 39  AttachedGarageYN              296275 non-null  object
 40  ParkingTotal                  349753 non-null  float64
 41  BuilderName                   17352 non-null   object
 42  PropertySubType               349478 non-null  object
 43  LotSizeAcres                  323198 non-null  float64
 44  SubdivisionName               130778 non-null  object
 45  BuyerOfficeAOR                329649 non-null  object
 46  YearBuilt                     349871 non-null  float64
 47  StreetNumberNumeric           349764 non-null  float64
 48  ListingId                     350179 non-null  object
 49  BathroomsTotalInteger         350123 non-null  float64
 50  City                          349941 non-null  object
 51  TaxYear                       0 non-null       float64
 52  BuildingAreaTotal             24874 non-null   float64
 53  BedroomsTotal                 350169 non-null  float64
 54  ContractStatusChangeDate      349590 non-null  object
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         31974 non-null   object
 57  PurchaseContractDate          349987 non-null  object
 58  ListingContractDate           350178 non-null  object
 59  BelowGradeFinishedArea        2095 non-null    float64
 60  BusinessType                  0 non-null       float64
 61  StateOrProvince               350179 non-null  object
 62  CoveredSpaces                 0 non-null       float64
 63  MiddleOrJuniorSchool          46368 non-null   object
 64  FireplaceYN                   349902 non-null  object
 65  Stories                       297759 non-null  float64
 66  HighSchool                    60297 non-null   object
 67  Levels                        318200 non-null  object
 68  LotSizeDimensions             17176 non-null   object
 69  LotSizeArea                   323645 non-null  float64
 70  MainLevelBedrooms             204289 non-null  float64
 71  NewConstructionYN             324140 non-null  object
 72  GarageSpaces                  334876 non-null  float64
 73  HighSchoolDistrict            253476 non-null  object
 74  PostalCode                    350177 non-null  object
 75  AssociationFee                270874 non-null  float64
 76  LotSizeSquareFeet             323528 non-null  float64
 77  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 78  OriginatingSystemName         55712 non-null   object
 79  OriginatingSystemSubName      55712 non-null   object
 80  BuyerAgencyCompensationType   46136 non-null   object
 81  BuyerAgencyCompensation       46125 non-null   float64
dtypes: float64(29), int64(3), object(50)
memory usage: 219.1+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 547162 entries, 0 to 547161
Data columns (total 84 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   OriginalListPrice             546373 non-null  float64
 1   ListingKey                    547162 non-null  int64
 2   ListAgentEmail                545656 non-null  object
 3   CloseDate                     159066 non-null  object
 4   ClosePrice                    137681 non-null  float64
 5   ListAgentFirstName            542808 non-null  object
 6   ListAgentLastName             547120 non-null  object
 7   Latitude                      466915 non-null  float64
 8   Longitude                     466915 non-null  float64
 9   UnparsedAddress               546380 non-null  object
 10  PropertyType                  547162 non-null  object
 11  LivingArea                    546610 non-null  float64
 12  ListPrice                     547162 non-null  float64
 13  DaysOnMarket                  547162 non-null  int64
 14  ListOfficeName                547162 non-null  object
 15  BuyerOfficeName               149887 non-null  object
 16  CoListOfficeName              122363 non-null  object
 17  ListAgentFullName             547070 non-null  object
 18  CoListAgentFirstName          121867 non-null  object
 19  CoListAgentLastName           122270 non-null  object
 20  BuyerAgentMlsId               151916 non-null  object
 21  BuyerAgentFirstName           151330 non-null  object
 22  BuyerAgentLastName            152024 non-null  object
 23  FireplacesTotal               0 non-null       float64
 24  AssociationFeeFrequency       233360 non-null  object
 25  AboveGradeFinishedArea        0 non-null       float64
 26  ListingKeyNumeric             547162 non-null  int64
 27  MLSAreaMajor                  472674 non-null  object
 28  TaxAnnualAmount               0 non-null       float64
 29  CountyOrParish                547162 non-null  object
 30  PropertyType.1                547162 non-null  object
 31  MlsStatus                     547162 non-null  object
 32  ElementarySchool              65476 non-null   object
 33  ListAgentFirstName.1          542808 non-null  object
 34  AttachedGarageYN              451713 non-null  object
 35  ParkingTotal                  547142 non-null  float64
 36  BuilderName                   25362 non-null   object
 37  PropertySubType               545899 non-null  object
 38  LotSizeAcres                  502132 non-null  float64
 39  SubdivisionName               201207 non-null  object
 40  BuyerOfficeAOR                140374 non-null  object
 41  YearBuilt                     546235 non-null  float64
 42  DaysOnMarket.1                547162 non-null  int64
 43  BuyerAgencyCompensationType   79013 non-null   object
 44  StreetNumberNumeric           546192 non-null  float64
 45  LivingArea.1                  546610 non-null  float64
 46  ListingId                     547162 non-null  object
 47  BathroomsTotalInteger         547107 non-null  float64
 48  City                          546585 non-null  object
 49  BuyerAgencyCompensation       78993 non-null   float64
 50  TaxYear                       0 non-null       float64
 51  BuildingAreaTotal             48352 non-null   float64
 52  BedroomsTotal                 547029 non-null  float64
 53  ContractStatusChangeDate      540851 non-null  object
 54  Longitude.1                   466915 non-null  float64
 55  ElementarySchoolDistrict      0 non-null       float64
 56  CoBuyerAgentFirstName         13696 non-null   object
 57  PurchaseContractDate          261486 non-null  object
 58  ListingContractDate           547162 non-null  object
 59  BelowGradeFinishedArea        3087 non-null    float64
 60  BusinessType                  0 non-null       float64
 61  Latitude.1                    466915 non-null  float64
 62  ListPrice.1                   547162 non-null  float64
 63  StateOrProvince               547108 non-null  object
 64  CoveredSpaces                 0 non-null       float64
 65  MiddleOrJuniorSchool          65501 non-null   object
 66  FireplaceYN                   546590 non-null  object
 67  Stories                       450689 non-null  float64
 68  HighSchool                    85892 non-null   object
 69  Levels                        487161 non-null  object
 70  ListAgentLastName.1           547120 non-null  object
 71  CloseDate.1                   159066 non-null  object
 72  LotSizeDimensions             28532 non-null   object
 73  LotSizeArea                   502986 non-null  float64
 74  MainLevelBedrooms             296677 non-null  float64
 75  NewConstructionYN             509566 non-null  object
 76  GarageSpaces                  516917 non-null  float64
 77  HighSchoolDistrict            382793 non-null  object
 78  PostalCode                    547149 non-null  object
 79  BuyerOfficeName.1             149887 non-null  object
 80  AssociationFee                414739 non-null  float64
 81  LotSizeSquareFeet             502812 non-null  float64
 82  MiddleOrJuniorSchoolDistrict  0 non-null       float64
 83  UnparsedAddress.1             546379 non-null  object
dtypes: float64(33), int64(4), object(47)
memory usage: 350.7+ MB

Part2:Missing Value Analysis

In [10]:
#Step 1. Build Missing Value Summary
def missing_summary(df):

    summary = pd.DataFrame({
        "Missing Count": df.isnull().sum(),
        "Missing %": (df.isnull().mean() * 100).round(2)
    })

    return summary.sort_values("Missing %", ascending=False)

sold_missing = missing_summary(sold)
listing_missing = missing_summary(listing)
sold_missing.head(20)

                              Missing Count  Missing %
BusinessType                         350179     100.00
CoveredSpaces                        350179     100.00
TaxAnnualAmount                      350179     100.00
TaxYear                              350179     100.00
ElementarySchoolDistrict             350179     100.00
FireplacesTotal                      350179     100.00
AboveGradeFinishedArea               350179     100.00
MiddleOrJuniorSchoolDistrict         350179     100.00
WaterfrontYN                         349960      99.94
BelowGradeFinishedArea               348084      99.40
BasementYN                           343313      98.04
LotSizeDimensions                    333003      95.10
BuilderName                          332827      95.04
BuildingAreaTotal                    325305      92.90
CoBuyerAgentFirstName                318205      90.87
ElementarySchool                     304167      86.86
BuyerAgencyCompensationType          304043      86.83
BuyerAgencyCompensation              304054      86.83
MiddleOrJuniorSchool                 303811      86.76
OriginatingSystemSubName             294467      84.09

In [12]:
#Step 2.  columns with >90% missing values
sold_high_missing = sold_missing[
    sold_missing["Missing %"] > 90
]

listing_high_missing = listing_missing[
    listing_missing["Missing %"] > 90
]
print(len(sold_high_missing))
sold_high_missing

15

                              Missing Count  Missing %
BusinessType                         350179     100.00
CoveredSpaces                        350179     100.00
TaxAnnualAmount                      350179     100.00
TaxYear                              350179     100.00
ElementarySchoolDistrict             350179     100.00
FireplacesTotal                      350179     100.00
AboveGradeFinishedArea               350179     100.00
MiddleOrJuniorSchoolDistrict         350179     100.00
WaterfrontYN                         349960      99.94
BelowGradeFinishedArea               348084      99.40
BasementYN                           343313      98.04
LotSizeDimensions                    333003      95.10
BuilderName                          332827      95.04
BuildingAreaTotal                    325305      92.90
CoBuyerAgentFirstName                318205      90.87

In [ ]:
#Step 3：Save report

sold_missing.to_csv(
    "sold_missing_summary.csv",
    index=True
)

listing_missing.to_csv(
    "listing_missing_summary.csv",
    index=True
)